"""empty message

Revision ID: cc84a57d84fa
Revises: d8de2c92d354
Create Date: 2024-08-23 17:25:10.454707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc84a57d84fa'
down_revision = 'd8de2c92d354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('post_foreignkey', 'post', ['post'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('post_foreignkey', type_='foreignkey')
        batch_op.drop_column('post')

    # ### end Alembic commands ###
